### ISSUE TITLE
compatibilità plone 6

### ISSUE THREAD

**Issue by sherpya** [RedTurtle/design.plone.policy#37]
Il pacchetto non sembra compatbile con plone 6, sto provando con plone 6.0.0.2, questo sembra related:
https://github.com/RedTurtle/dist.design.plone/pull/6

```
+ which python3
+ python3 -c 'import sys; print((int(sys.version_info[0]), int(sys.version_info[1])) >= tuple(map(int, '\''3.8'\''.split('\''.'\''))))'
+ PYTHONWARNINGS=ignore
+ ./bin/runwsgi instance/etc/zope.ini
2023-01-18 19:44:51,340 INFO    [chameleon.config:38][MainThread] directory cache: /opt/plone/backend/instance/var/cache.
2023-01-18 19:44:53,156 INFO    [collective.honeypot:19][MainThread] Honey pot field: 'protected_1'
2023-01-18 19:44:53,156 INFO    [collective.honeypot:28][MainThread] Extra protected actions: set()
2023-01-18 19:44:53,156 INFO    [collective.honeypot:42][MainThread] Whitelisted actions: {'atct_edit', 'at_validate_field', 'z3cform_validate_field', 'edit', 'kssValidateField', 'jq_reveal_email'}
2023-01-18 19:44:53,156 INFO    [collective.honeypot:46][MainThread] Whitelisted action start strings: set()
2023-01-18 19:44:53,156 INFO    [collective.honeypot:50][MainThread] Ignored form fields: set()
2023-01-18 19:44:53,156 INFO    [collective.honeypot:75][MainThread] Accepted log level: 20
2023-01-18 19:44:53,156 INFO    [collective.honeypot:78][MainThread] Spammer log level: 40
2023-01-18 19:44:53,177 INFO    [collective.honeypot:7][MainThread] Loading plone5 patches.
2023-01-18 19:44:53,177 INFO    [collective.honeypot:18][MainThread] Extra protected actions: {'contact-info', 'send_feedback_site', 'sendto', 'register', 'sendto_form'}
2023-01-18 19:44:53,467 INFO    [plone.volto:22][MainThread] Aliasing collective.folderish classes to plone.volto classes.
Traceback (most recent call last):
  File "/opt/plone/backend/./bin/runwsgi", line 8, in <module>
    sys.exit(main())
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 200, in invoke
    app = context.app_context.create()
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/opt/plone/backend/lib/python3.9/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/App/startup.py", line 126, in startup
    load_zcml()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/App/startup.py", line 41, in load_zcml
    load_site()
  File "/opt/plone/backend/lib/python3.9/site-packages/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/opt/plone/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 665, in file
    context.execute_actions()
  File "/opt/plone/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 783, in execute_actions
    for action in resolveConflicts(self.actions):
  File "/opt/plone/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 1832, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
zope.configuration.config.ConfigurationConflictError: Conflicting configuration actions
  For: ('adapter', (<InterfaceClass plone.schemaeditor.interfaces.ISchemaContext>, <InterfaceClass zope.schema.interfaces.IField>), <InterfaceClass plone.schemaeditor.interfaces.IFieldEditorExtender>, 'plone.schemaeditor.searchabletext')
    File "/opt/plone/backend/lib/python3.9/site-packages/collective/dexteritytextindexer/configure.zcml", line 51.4-57.10
          <adapter
              provides="plone.schemaeditor.interfaces.IFieldEditorExtender"
              for="plone.schemaeditor.interfaces.ISchemaContext
                   zope.schema.interfaces.IField"
              name="plone.schemaeditor.searchabletext"
              factory=".schemaeditor.get_searchabletext_schema"
              />
    File "/opt/plone/backend/lib/python3.9/site-packages/plone/app/dexterity/textindexer/configure.zcml", line 48.4-54.10
          <adapter
              provides="plone.schemaeditor.interfaces.IFieldEditorExtender"
              for="plone.schemaeditor.interfaces.ISchemaContext
                   zope.schema.interfaces.IField"
              name="plone.schemaeditor.searchabletext"
              factory=".schemaeditor.get_searchabletext_schema"
              />
make: *** [Makefile:158: start] Error 1
```

**Comment by pnicolli** [comment]
Ad oggi il pacchetto nella sua versione stabile non è compatibile con Plone 6, lo confermo, ma la compatibilità è già in lavorazione assieme alle nuove linee guida per la PA. Esistono delle pre-release sperimentali su pypi, ma sottolineo che sono ancora altamente sperimentali. Ci stiamo lavorando molto in questo periodo quindi consiglio di tenere d'occhio l'evoluzione delle cose.

**Comment by mamico** [comment]
Ciao @sherpya ora il main branch del progetto e le versioni 5.0.0 e successive sono compatibili con Plone 6.0

Riporto dal README, l'attuale mappa di compatibilità tra i prodotti.

- Plone 6.0, design.plone.policy 5.*, design.plone.contenttypes 6.*
- Plone 5.2, design.plone.policy 4.*, design.plone.contenttypes 5.*
